from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional


class Side(Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


@dataclass
class TradeSignal:
    """
    Represents a trading signal generated by a strategy.
    
    Fields:
        symbol: Stock symbol (e.g., "AAPL")
        side: Buy or sell action
        qty: Number of shares to trade
        order_type: Type of order to place
        confidence: Signal confidence score (0.0 to 1.0)
        timestamp: When the signal was generated
        strategy: Name of the strategy that generated this signal
        price: Target price (optional, for limit orders)
        stop_price: Stop price (optional, for stop orders)
        metadata: Additional strategy-specific data
    """
    symbol: str
    side: Side
    qty: int
    order_type: OrderType
    confidence: float
    timestamp: datetime
    strategy: str
    price: Optional[float] = None
    stop_price: Optional[float] = None
    metadata: Optional[dict] = None
    
    def __post_init__(self):
        """Validate the trade signal after creation."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")
        
        if self.qty <= 0:
            raise ValueError("Quantity must be positive")
        
        if self.order_type == OrderType.LIMIT and self.price is None:
            raise ValueError("Limit orders require a price")
            
        if self.order_type in [OrderType.STOP, OrderType.STOP_LIMIT] and self.stop_price is None:
            raise ValueError("Stop orders require a stop_price")
    
    def to_dict(self) -> dict:
        """Convert to dictionary for database storage."""
        return {
            'symbol': self.symbol,
            'side': self.side.value,
            'qty': self.qty,
            'order_type': self.order_type.value,
            'confidence': self.confidence,
            'timestamp': self.timestamp,
            'strategy': self.strategy,
            'price': self.price,
            'stop_price': self.stop_price,
            'metadata': self.metadata
        }